/**
 * Partner Portal — Mock Data
 *
 * Scaffold data for the partner portal. Typed against the cross-org entity
 * model in `@repo/api` so screens are already shaped for the real backend.
 * Swap these arrays for partner-scoped tRPC queries when the migration lands.
 *
 * The story: "Northgate Security" is an installer that has put locks into
 * three DIFFERENT customer orgs — the cross-org reach that distinguishes a
 * partner from an ordinary org member.
 */

import type {
  Partner,
  PartnerInstallation,
  PartnerDevice,
  PartnerAccessEvent,
  PartnerResource,
} from "@repo/api";

export const mockPartner: Partner = {
  id: "partner-northgate",
  slug: "northgate-security",
  name: "Northgate Security",
  logoUrl: null,
  brandColor: "#0ea5e9",
  contactEmail: "ops@northgate-security.example",
  tier: "premium",
};

export const mockInstallations: PartnerInstallation[] = [
  {
    id: "inst-1",
    partnerId: mockPartner.id,
    orgRefId: "org-acme",
    orgName: "Acme Coworking",
    siteRefId: "site-acme-hq",
    siteName: "Acme HQ — Level 4",
    location: "Sydney, NSW",
    installedAt: "2025-11-02",
    deviceCount: 12,
    healthyDeviceCount: 11,
  },
  {
    id: "inst-2",
    partnerId: mockPartner.id,
    orgRefId: "org-acme",
    orgName: "Acme Coworking",
    siteRefId: "site-acme-annex",
    siteName: "Acme Annex",
    location: "Sydney, NSW",
    installedAt: "2025-12-10",
    deviceCount: 6,
    healthyDeviceCount: 6,
  },
  {
    id: "inst-3",
    partnerId: mockPartner.id,
    orgRefId: "org-riverside",
    orgName: "Riverside Apartments",
    siteRefId: "site-riverside-tower",
    siteName: "Riverside Tower",
    location: "Melbourne, VIC",
    installedAt: "2026-01-18",
    deviceCount: 24,
    healthyDeviceCount: 21,
  },
  {
    id: "inst-4",
    partnerId: mockPartner.id,
    orgRefId: "org-brightpath",
    orgName: "BrightPath Schools",
    siteRefId: "site-brightpath-west",
    siteName: "BrightPath West Campus",
    location: "Brisbane, QLD",
    installedAt: "2026-03-04",
    deviceCount: 9,
    healthyDeviceCount: 7,
  },
];

export const mockDevices: PartnerDevice[] = [
  {
    id: "dev-1",
    partnerId: mockPartner.id,
    orgRefId: "org-acme",
    orgName: "Acme Coworking",
    siteRefId: "site-acme-hq",
    siteName: "Acme HQ — Level 4",
    externalDeviceId: "NG-AC-0412",
    name: "Front Entrance",
    deviceType: "Smart Deadbolt",
    health: "online",
    firmwareVersion: "3.4.1",
    batteryPercent: 82,
    lastSeenAt: "2026-07-14T09:41:00Z",
    installedAt: "2025-11-02",
  },
  {
    id: "dev-2",
    partnerId: mockPartner.id,
    orgRefId: "org-acme",
    orgName: "Acme Coworking",
    siteRefId: "site-acme-hq",
    siteName: "Acme HQ — Level 4",
    externalDeviceId: "NG-AC-0413",
    name: "Server Room",
    deviceType: "Access Controller",
    health: "degraded",
    firmwareVersion: "3.3.0",
    batteryPercent: null,
    lastSeenAt: "2026-07-14T08:12:00Z",
    installedAt: "2025-11-02",
  },
  {
    id: "dev-3",
    partnerId: mockPartner.id,
    orgRefId: "org-riverside",
    orgName: "Riverside Apartments",
    siteRefId: "site-riverside-tower",
    siteName: "Riverside Tower",
    externalDeviceId: "NG-RV-1180",
    name: "Lobby Turnstile",
    deviceType: "Access Controller",
    health: "online",
    firmwareVersion: "3.4.1",
    batteryPercent: null,
    lastSeenAt: "2026-07-14T09:55:00Z",
    installedAt: "2026-01-18",
  },
  {
    id: "dev-4",
    partnerId: mockPartner.id,
    orgRefId: "org-riverside",
    orgName: "Riverside Apartments",
    siteRefId: "site-riverside-tower",
    siteName: "Riverside Tower",
    externalDeviceId: "NG-RV-1207",
    name: "Unit 14B",
    deviceType: "Smart Deadbolt",
    health: "offline",
    firmwareVersion: "3.2.5",
    batteryPercent: 9,
    lastSeenAt: "2026-07-12T22:03:00Z",
    installedAt: "2026-01-18",
  },
  {
    id: "dev-5",
    partnerId: mockPartner.id,
    orgRefId: "org-brightpath",
    orgName: "BrightPath Schools",
    siteRefId: "site-brightpath-west",
    siteName: "BrightPath West Campus",
    externalDeviceId: "NG-BP-3301",
    name: "Gym Side Door",
    deviceType: "Smart Deadbolt",
    health: "maintenance",
    firmwareVersion: "3.4.1",
    batteryPercent: 64,
    lastSeenAt: "2026-07-14T07:30:00Z",
    installedAt: "2026-03-04",
  },
  {
    id: "dev-6",
    partnerId: mockPartner.id,
    orgRefId: "org-brightpath",
    orgName: "BrightPath Schools",
    siteRefId: "site-brightpath-west",
    siteName: "BrightPath West Campus",
    externalDeviceId: "NG-BP-3302",
    name: "Main Reception",
    deviceType: "Access Controller",
    health: "online",
    firmwareVersion: "3.4.1",
    batteryPercent: null,
    lastSeenAt: "2026-07-14T09:58:00Z",
    installedAt: "2026-03-04",
  },
];

export const mockAccessEvents: PartnerAccessEvent[] = [
  {
    id: "evt-1",
    partnerId: mockPartner.id,
    orgName: "Riverside Apartments",
    siteName: "Riverside Tower",
    deviceName: "Lobby Turnstile",
    eventType: "unlock",
    actorName: "Resident • Unit 9C",
    outcome: "granted",
    timestamp: "2026-07-14T09:52:00Z",
  },
  {
    id: "evt-2",
    partnerId: mockPartner.id,
    orgName: "Acme Coworking",
    siteName: "Acme HQ — Level 4",
    deviceName: "Server Room",
    eventType: "access_denied",
    actorName: "Guest badge 4821",
    outcome: "denied",
    timestamp: "2026-07-14T09:47:00Z",
  },
  {
    id: "evt-3",
    partnerId: mockPartner.id,
    orgName: "BrightPath Schools",
    siteName: "BrightPath West Campus",
    deviceName: "Main Reception",
    eventType: "unlock",
    actorName: "Staff • J. Okoro",
    outcome: "granted",
    timestamp: "2026-07-14T08:59:00Z",
  },
  {
    id: "evt-4",
    partnerId: mockPartner.id,
    orgName: "Riverside Apartments",
    siteName: "Riverside Tower",
    deviceName: "Unit 14B",
    eventType: "tamper",
    actorName: null,
    outcome: "error",
    timestamp: "2026-07-12T22:03:00Z",
  },
  {
    id: "evt-5",
    partnerId: mockPartner.id,
    orgName: "Acme Coworking",
    siteName: "Acme Annex",
    deviceName: "Front Entrance",
    eventType: "unlock",
    actorName: "Member • S. Patel",
    outcome: "granted",
    timestamp: "2026-07-14T07:15:00Z",
  },
];

export const mockResources: PartnerResource[] = [
  {
    id: "res-1",
    title: "Northgate Installer Handbook",
    description:
      "Wiring diagrams, mounting templates and commissioning steps for every supported lock model.",
    category: "guide",
    url: "#",
    updatedAt: "2026-06-28",
    coBranded: true,
  },
  {
    id: "res-2",
    title: "Firmware 3.4.1 Release Notes",
    description:
      "Battery-reporting fixes and a new tamper-detection threshold. Recommended for all deadbolts.",
    category: "firmware",
    url: "#",
    updatedAt: "2026-07-01",
    coBranded: false,
  },
  {
    id: "res-3",
    title: "Co-branded Customer One-Pager",
    description:
      "Editable PDF you can hand to prospects — carries both the Zezamii and Northgate marks.",
    category: "marketing",
    url: "#",
    updatedAt: "2026-05-19",
    coBranded: true,
  },
  {
    id: "res-4",
    title: "Priority Support Line",
    description:
      "Premium-tier partners get a dedicated escalation channel with a 4-hour response target.",
    category: "support",
    url: "#",
    updatedAt: "2026-04-02",
    coBranded: false,
  },
];
